#declare Planet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
LightGray } } }

#declare JointPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
VLightGrey } } }

#declare ARDCPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
Red } } }

#declare CCPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
SeaGreen } } }

#declare CGBPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
SkyBlue } } }

#declare CJFPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
ForestGreen } } }

#declare CNCPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
BrightGold } } }

#declare CSJPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
DimGrey } } }

#declare CSVPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
rgb <0.07 0.27 0.4> } } }

#declare CWPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
Firebrick } } }

#declare DCPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
Scarlet } } }

#declare FSPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
Coral } } }

#declare FRRPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
DarkOrchid } } }

#declare FWLPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
Med_Purple } } }

#declare LCPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
NeonBlue } } }

#declare SICPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
SummerSky } } }

#declare THPlanet = sphere { <0, 0, 0>, 3.375 texture { pigment { color
Grey } } }
