#declare ARPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <1, 0, 0, 0.9> } finish { ambient 0.25 brilliance 3
diffuse 0.5 metallic reflection 0.45 roughness 0.0125 specular 0.80 } }

#declare CCPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.137255, 0.556863, 0.419608, 0.9> } finish { ambient
0.25 brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare CGBPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.196078, 0.6, 0.8, 0.9> } finish { ambient 0.25
brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare CJFPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.137255, 0.556863, 0.137255, 0.9> } finish { ambient
0.25 brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare CNCPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.85, 0.85, 0.10, 0.9> } finish { ambient 0.25
brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare CSJPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.329412, 0.329412, 0.329412, 0.9> } finish { ambient
0.25 brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare CSVPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.07, 0.27, 0.4, 0.9> } finish { ambient 0.25 brilliance
3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125 specular 0.80 }
}

#declare CWPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.556863, 0.137255, 0.137255, 0.9> } finish { ambient
0.25 brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare DCPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.55, 0.09, 0.09, 0.9> } finish { ambient 0.25
brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare FSPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <1.0, 0.498039, 0.0, 0.9> } finish { ambient 0.25
brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare FRRPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.6, 0.196078, 0.8 0.9> } finish { ambient 0.25
brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare FWLPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.73, 0.16, 0.96, 0.9> } finish { ambient 0.25
brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare LCPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.30, 0.30, 1.00, 0.9> } finish { ambient 0.25
brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare SICPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.22, 0.69, 0.87, 0.9> } finish { ambient 0.25
brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare THPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7,
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.752941, 0.752941, 0.752941, 0.9> } finish { ambient
0.25 brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare PPrism = prism { linear_sweep linear_spline -0.5, 0.5, 7, 
<7.5, 13>, <15, 0>, <7.5, -13>, <-7.5, -13>, <-15, 0>, <-7.5, 13>, <7.5, 13>
pigment { rgbf <0.658824, 0.658824, 0.658824, 0.9> } finish { ambient
0.25 brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } }

#declare HexBorder1 = cylinder { <-7.5, 0, 0>, <7.5, 0, 0>, 0.75 texture
{ pigment { rgbf <0.90, 0.90, 0.90, 0.75> } finish { ambient 0.25
brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } } }

#declare HexBorder2 = cylinder { <3.75, 0, -6.5>, <-3.75, 0, 6.5>, 0.75
texture { pigment { rgbf <0.90, 0.90, 0.90, 0.75> } finish { ambient
0.25 brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } } }

#declare HexBorder3 = cylinder { <3.75, 0, 6.5>, <-3.75, 0, -6.5>, 0.75
texture { pigment { rgbf <0.90, 0.90, 0.90, 0.75> } finish { ambient
0.25 brilliance 3 diffuse 0.5 metallic reflection 0.45 roughness 0.0125
specular 0.80 } } }
